<?php

/**
 * @file
 * Contains dimport.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dimport_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dimport module.
    case 'help.page.dimport':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 data import') . '</p>';
      return $output;

    default:
  }
}
