
# Source menu items definition
entity.dimport_source.collection:
  title: 'Source'
  route_name: entity.dimport_source.collection
  description: 'List Source (bundles)'
  parent: dimport.admin.page_root
  weight: 99

