<?php

/**
 * @file
 * Contains dimport_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dimport_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dimport_config module.
    case 'help.page.dimport_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dimport config module') . '</p>';
      return $output;

    default:
  }
}
